apiVersion: secrets-store.csi.k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "secure-fintech.fullname" . }}-kv
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "{{ .Values.kv.uamiClientId }}"
    keyvaultName: "{{ .Values.kv.name }}"
    tenantId: "{{ .Values.kv.tenantId }}"
    objects: |
      array:
{{- range .Values.kv.secrets }}
        - objectName: {{ .name }}
          objectType: secret
          objectVersion: ""
{{- end }}
  secretObjects:
  - secretName: {{ .Values.kv.k8sSecretName }}
    type: Opaque
    data:
{{- range .Values.kv.secrets }}
    - objectName: {{ .name }}
      key: {{ .key }}
{{- end }}
